repos:
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
        types_or: [python, rst, markdown]
        additional_dependencies: [tomli]
        args: ['-L missings']  # missings is a word
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: debug-statements
    -   id: trailing-whitespace
-   repo: https://github.com/Quantco/pre-commit-mirrors-black
    rev: 24.4.2
    hooks:
    - id: black-conda
      args:
        - --safe
        - --target-version=py38
- repo: https://github.com/Quantco/pre-commit-mirrors-isort
  rev: 5.13.2
  hooks:
  - id: isort-conda
    additional_dependencies: [toml]
- repo: https://github.com/Quantco/pre-commit-mirrors-flake8
  rev: 7.1.1
  hooks:
  - id: flake8-conda
    additional_dependencies: [-c, conda-forge, flake8-docstrings=1.5.0, flake8-rst-docstrings=0.0.14]
- repo: https://github.com/Quantco/pre-commit-mirrors-mypy
  rev: "1.10.1"
  hooks:
  - id: mypy-conda
- repo: https://github.com/Quantco/pre-commit-mirrors-pyupgrade
  rev: 3.15.2
  hooks:
  - id: pyupgrade-conda
    args:
      - --py38-plus