name: icu-benchmarks
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - click
  - glum>=3.1
  - tabmat>=4.1
  - numpy>=2.1
  - pandas
  - polars
  - pytest
  - gin-config
  - pyarrow
  - tabulate
  - ivmodels
  - lightgbm
  - pip:
    - "git+git@github.com:mlondschien/anchorboost.git"