name: icu-benchmarks
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - click
  - glum>=3.1
  - tabmat>=4.1
  - numpy>=2.1
  - pandas
  - polars
  - pytest
  - gin-config
  - pyarrow
  - cffi  # To support LGBM predictions from arrow tables / polars
  - tabulate
  - ivmodels
  - anchorboosting
  - scikit-learn
  - lightgbm
  - pip:
    - "git+https://github.com/eth-mds/icu-features.git"