name: icu-benchmarks
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - click
  - glum>=3.0
  - numpy>=2.1
  - pandas
  - polars
  - pytest
  - gin-config
  - pyarrow
  - tabulate